### ISSUE TITLE
Path to godot/ directory in the source project gets hardcoded in the binary

### ISSUE THREAD

**Issue by tad-lispy** [rand0m-cloud/bevy_jam#2]
@rand0m-cloud and I discussed it today over video call. The problem is of relatively low priority, but I'll summarize below the best I can so we won't forget.

This line seems to be the culprit:

https://github.com/rand0m-cloud/bevy_jam/blob/47b76dea14bc07af079efcebfb1c1f112c096619/run_godot.rs#L9

One of the effects is that the game compiled with `nix build` doesn't run for me. I'm getting the following:

    $ result/bin/run_game
    /build/6rs1g5jhs50dzb7mxlfgcbjlkfn9cvl8-source
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', run_godot.rs:11:10
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I can run without issues with `cargo run` or `./target/release/run_game`:

    $ ./target/release/run_game
    /home/tad/Projects/bevy_jam
    Godot Engine v3.4.4.stable.custom_build - https://godotengine.org/
    OpenGL ES 2.0 Renderer: AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.59)
    OpenGL ES Batching: ON

In both cases the first line shows the path to the directory where godot/ subdirectory should be. In case of nix build, this directory (`/build/....-source`) was inside a build container and doesn't exist on the host machine.

I think this will be a problem when we try to distribute the binary.

**Comment by tad-lispy** [comment]
This might contain some hints to improve the situation: <https://stackoverflow.com/a/67516503/1151982>.

The whole `get_output_path` function seems unnecessary. There is `OUT_DIR` variable that contains the same information, probably covering some edge cases too.

Here is a discussion about getting a path relative to the location of the binary: <https://www.reddit.com/r/AskProgramming/comments/d19jm7/rust_whats_the_idiomatic_way_best_way_to_read/>.

If we put these two together, we can copy the `godot/` directory to the output directory and then resolve it's path on runtime. Would that be a good idea?

**Comment by rand0m-cloud** [comment]
Closing because this is only an issue for developers, end-users are given the Godot exported game and don't even see this `run_godot` binary. However, the threads linked here will be useful when I return back to `bevy_godot` development.
